// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using CompatibilityApp.Infrastructure.Entities;
using Microsoft.EntityFrameworkCore;

namespace CompatibilityApp.Infrastructure.Data;

public partial class CompatibilityDBContext : DbContext
{
    public CompatibilityDBContext(DbContextOptions<CompatibilityDBContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Person> People { get; set; }

    public virtual DbSet<PersonRating> PersonRatings { get; set; }

    public virtual DbSet<PersonSeason> PersonSeasons { get; set; }

    public virtual DbSet<RatingType> RatingTypes { get; set; }

    public virtual DbSet<Relationship> Relationships { get; set; }

    public virtual DbSet<RelationshipRating> RelationshipRatings { get; set; }

    public virtual DbSet<RelationshipSeason> RelationshipSeasons { get; set; }

    public virtual DbSet<Season> Seasons { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<PersonRating>(entity =>
        {
            entity.HasOne(d => d.RatingType).WithMany(p => p.PersonRatings).HasConstraintName("FK_PersonRating_RatingType");

            entity.HasOne(d => d.PersonSeason).WithMany(p => p.PersonRatings)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PersonRating_PersonSeason");
        });

        modelBuilder.Entity<PersonSeason>(entity =>
        {
            entity.HasOne(d => d.Person).WithMany(p => p.PersonSeasons)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PersonSeason_Person");

            entity.HasOne(d => d.SeasonNavigation).WithMany(p => p.PersonSeasons)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PersonSeason_Season");
        });

        modelBuilder.Entity<Relationship>(entity =>
        {
            entity.HasKey(e => e.RelationshipId).HasName("PK_Relationship_1");

            entity.HasOne(d => d.PersonId1Navigation).WithMany(p => p.RelationshipPersonId1Navigations)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Relationship_Person_1");

            entity.HasOne(d => d.PersonId2Navigation).WithMany(p => p.RelationshipPersonId2Navigations)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Relationship_Person_2");
        });

        modelBuilder.Entity<RelationshipRating>(entity =>
        {
            entity.HasOne(d => d.RatingType).WithMany(p => p.RelationshipRatings).HasConstraintName("FK_RelationshipRating_RatingType");

            entity.HasOne(d => d.RelationshipSeason).WithMany(p => p.RelationshipRatings)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_RelationshipRating_RelationshipSeason");
        });

        modelBuilder.Entity<RelationshipSeason>(entity =>
        {
            entity.HasOne(d => d.Relationship).WithMany(p => p.RelationshipSeasons)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_RelationshipSeason_Relationship");

            entity.HasOne(d => d.SeasonNavigation).WithMany(p => p.RelationshipSeasons)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_RelationshipSeason_Season");
        });

        modelBuilder.Entity<Season>(entity =>
        {
            entity.Property(e => e.SeasonNum).ValueGeneratedNever();
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}