// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CompatibilityApp.Infrastructure.Entities;

[Table("Person", Schema = "DayFiance")]
public partial class Person
{
    [Key]
    [Column("PersonID")]
    public int PersonId { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string FirstName { get; set; } = null!;

    [StringLength(50)]
    [Unicode(false)]
    public string LastName { get; set; } = null!;

    [StringLength(100)]
    [Unicode(false)]
    public string HomeCity { get; set; } = null!;

    [StringLength(100)]
    [Unicode(false)]
    public string HomeCountry { get; set; } = null!;

    [Column(TypeName = "datetime")]
    public DateTime DateOfBirth { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string PersonType { get; set; } = null!;

    [StringLength(10)]
    public string Gender { get; set; } = null!;

    [StringLength(200)]
    [Unicode(false)]
    public string ImagePath { get; set; } = null!;

    [InverseProperty("Person")]
    public virtual ICollection<PersonSeason> PersonSeasons { get; set; } = new List<PersonSeason>();

    [InverseProperty("PersonId1Navigation")]
    public virtual ICollection<Relationship> RelationshipPersonId1Navigations { get; set; } = new List<Relationship>();

    [InverseProperty("PersonId2Navigation")]
    public virtual ICollection<Relationship> RelationshipPersonId2Navigations { get; set; } = new List<Relationship>();
}