// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CompatibilityApp.Infrastructure.Entities;

[PrimaryKey("PersonId", "Season", "RatingTypeId")]
[Table("PersonRating", Schema = "DayFiance")]
public partial class PersonRating
{
    [Key]
    [Column("PersonID")]
    public int PersonId { get; set; }

    [Key]
    public short Season { get; set; }

    [Key]
    [Column("RatingTypeID")]
    public int RatingTypeId { get; set; }

    [Column(TypeName = "decimal(5, 2)")]
    public decimal RatingValue { get; set; }

    [ForeignKey("PersonId, Season")]
    [InverseProperty("PersonRatings")]
    public virtual PersonSeason PersonSeason { get; set; } = null!;

    [ForeignKey("RatingTypeId")]
    [InverseProperty("PersonRatings")]
    public virtual RatingType RatingType { get; set; } = null!;
}