// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CompatibilityApp.Infrastructure.Entities;

[Table("RatingType", Schema = "DayFiance")]
public partial class RatingType
{
    [Key]
    [Column("RatingTypeID")]
    public int RatingTypeId { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string RatingName { get; set; } = null!;

    [Column(TypeName = "decimal(10, 2)")]
    public decimal RatingWeight { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string RatingCategory { get; set; } = null!;

    [InverseProperty("RatingType")]
    public virtual ICollection<PersonRating> PersonRatings { get; set; } = new List<PersonRating>();

    [InverseProperty("RatingType")]
    public virtual ICollection<RelationshipRating> RelationshipRatings { get; set; } = new List<RelationshipRating>();
}