// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CompatibilityApp.Infrastructure.Entities;

[Table("Relationship", Schema = "DayFiance")]
public partial class Relationship
{
    [Key]
    [Column("RelationshipID")]
    public int RelationshipId { get; set; }

    [Column("Person_id_1")]
    public int PersonId1 { get; set; }

    [Column("Person_id_2")]
    public int PersonId2 { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string RelationshipType { get; set; } = null!;

    [StringLength(200)]
    [Unicode(false)]
    public string ImagePath { get; set; } = null!;

    [ForeignKey("PersonId1")]
    [InverseProperty("RelationshipPersonId1Navigations")]
    public virtual Person PersonId1Navigation { get; set; } = null!;

    [ForeignKey("PersonId2")]
    [InverseProperty("RelationshipPersonId2Navigations")]
    public virtual Person PersonId2Navigation { get; set; } = null!;

    [InverseProperty("Relationship")]
    public virtual ICollection<RelationshipSeason> RelationshipSeasons { get; set; } = new List<RelationshipSeason>();
}