// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CompatibilityApp.Infrastructure.Entities;

[PrimaryKey("Season", "RelationshipId")]
[Table("RelationshipSeason", Schema = "DayFiance")]
public partial class RelationshipSeason
{
    [Key]
    public short Season { get; set; }

    [Key]
    [Column("RelationshipID")]
    public int RelationshipId { get; set; }

    [ForeignKey("RelationshipId")]
    [InverseProperty("RelationshipSeasons")]
    public virtual Relationship Relationship { get; set; } = null!;

    [InverseProperty("RelationshipSeason")]
    public virtual ICollection<RelationshipRating> RelationshipRatings { get; set; } = new List<RelationshipRating>();

    [ForeignKey("Season")]
    [InverseProperty("RelationshipSeasons")]
    public virtual Season SeasonNavigation { get; set; } = null!;
}