// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CompatibilityApp.Infrastructure.Entities;

[Table("Season", Schema = "DayFiance")]
public partial class Season
{
    [Key]
    public short SeasonNum { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime AirDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime FilmingDate { get; set; }

    [InverseProperty("SeasonNavigation")]
    public virtual ICollection<PersonSeason> PersonSeasons { get; set; } = new List<PersonSeason>();

    [InverseProperty("SeasonNavigation")]
    public virtual ICollection<RelationshipSeason> RelationshipSeasons { get; set; } = new List<RelationshipSeason>();
}